# Site settings
name: Solid Groove Records
description: "Solid Groove Records is a young, independent Digital Label, founded 2014 by Danny Stompé, specialized in releasing high-quality underground Techno, Hard Techno, and Dark Techno"
# url: "https://solidgrooverecords.tk"
url: "https://dannysto.github.io/solidgroove"


# Delete the lines you don't need
# about 5 elements are recomended
# github_username:  dashingcode
#codepen_username: your_codepen_username_goes_here
facebook_username: solidgrooverecords
# vk_username: your_vk_username_goes_here
# twitter_username: your_twitter_username_goes_here
# google_plus_username: your_google_plus_username_goes_here
# linkedin_username: your_linked_in_username_goes_here
# vine_username:  your_vine_username_goes_here
instagram_username:  your_instagram_username_goes_here
# flickr_username: your_flickr_username_goes_here
beatport_username: solid-groove-records/36628
soundcloud_username:  solid-groove-records
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
juno_username:  Solid+Groove+Recordings
# tumblr_username: your_tumblr_username_goes_here
traxx_username: 16347/solid-groove-records
# lastfm_username: your_lastfm_username_goes_here
# blog_url: "/blog"
email: demo@solidgrooverecords
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://i1.sndcdn.com/avatars-000076582753-fqczb5-t500x500.jpg"


front_img: no
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
